# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='detail',
            new_name='details',
        ),
    ]
