# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180417_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
