# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180417_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
